object Deps {
    val kotlin_version = "1.3.0"
    val gradle_build_version = "3.2.0"
    val build_tools_version = "28.0.2"

    val coroutines_version = "1.0.0"
    val okhttp_version = "3.11.0"
    val moshi_version = "1.5.0"
    val rome_version = "1.7.1"
    val conscrypt_version = "1.4.1"

    val androidx_version = "1.0.0"
    val work_version = "1.0.0-alpha11"
    val constraintlayout_version = "2.0.0-alpha2"
    val recyclerview_version = "$androidx_version"
    val legacy_support_version = "$androidx_version"
    val appcompat_version = "1.0.2"
    val material_version = "$androidx_version"
    val preference_version = "$androidx_version"
    val test_runner_version = "1.1.0"
    val test_rules_version = "1.1.0"
    val paging_version = "2.0.0"
    val lifecycle_version = "2.0.0"
    val room_version = "2.0.0"

    val espresso_version = "3.1.0"
    val uiautomator_version = "2.2.0"
    val test_ext_junit_version = "1.0.0"
    val junit_version = "4.12"
}
